# Demo 2 - Demonstração - Aprendizagem Supervisionada

### Cybersecurity MBA - Inteligência Artificial e Machine Learning (SEG)

### Algoritmo para classificação de transações em possíveis fraudes/não fraude.

### Prof. Dr. Ahirton Lopes (profahirton.lopes@fiap.com.br)

Ref. - https://www.kaggle.com/pwnpen/payment

In [1]:
# Import de nossas bibliotecas

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (accuracy_score,precision_score,recall_score)

In [2]:
'''
# Upload de nosso arquivo.

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
'''

'\n# Upload de nosso arquivo.\n\nfrom google.colab import files\n\nuploaded = files.upload()\n\nfor fn in uploaded.keys():\n  print(\'User uploaded file "{name}" with length {length} bytes\'.format(\n      name=fn, length=len(uploaded[fn])))\n'

In [3]:
# Upload de nosso arquivo. Ref. - https://www.kaggle.com/pwnpen/payment
# Baixando nossa base de dados direto do repositório da disciplina (https://github.com/ahirtonlopes/Security-ML/) para o Google Colab

!curl -O https://raw.githubusercontent.com/ahirtonlopes/Security-ML/main/Aula2_Extras/payment_fraud.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1444k  100 1444k    0     0  1730k      0 --:--:-- --:--:-- --:--:-- 1732k

In [4]:
# Lendo dados a partir de nosso arquivo .csv
df = pd.read_csv('payment_fraud.csv')

In [5]:
# Amostragem de cabeçalho e cinco primeiras linhas de nosso dataset
df.sample(5)

,accountAgeDays,numItems,localTime,paymentMethod,paymentMethodAgeDays,label
4721,1223,1,4.524580,paypal,0.013889,0
12751,2,1,4.524580,creditcard,1.789583,0
22824,2000,1,4.748314,creditcard,0.000000,0
33672,538,1,4.836982,creditcard,0.000694,0
18534,131,1,5.034622,creditcard,130.228472,0

In [6]:
# Verificando linhas e partir do índice de nosso dataset
len(df.index)

39221

In [7]:
# Verificando colunas de nosso dataset
df.columns

Index(['accountAgeDays', 'numItems', 'localTime', 'paymentMethod',
       'paymentMethodAgeDays', 'label'],
      dtype='object')

In [8]:
# Verificando itens únicos de nossa coluna 'paymentMethod' de nosso dataset
(df['paymentMethod'].unique())

array(['paypal', 'storecredit', 'creditcard'], dtype=object)

In [9]:
# Agrupando número de itens de nossa coluna 'numItems' de nosso dataset
df.groupby('numItems').size().reset_index()

    numItems      0
0          1  37398
1          2   1348
2          3    164
3          4     42
4          5    168
5          6     15
6          7      5
7          8      5
8          9      1
9         10     71
10        11      1
11        12      1
12        15      1
13        29      1

In [10]:
# Tratando nossos dados da coluna 'pamentMethod' para formato numérico - Ref. https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html
df_one_hot = pd.get_dummies(df, columns=['paymentMethod'])

In [11]:
df_one_hot.sample(3)

,accountAgeDays,numItems,localTime,paymentMethodAgeDays,label,paymentMethod_creditcard,paymentMethod_paypal,paymentMethod_storecredit
5427,1152,1,4.461622,240.713194,0,False,True,False
19268,534,1,4.921318,0.000000,0,True,False,False
27004,21,1,4.524580,20.906250,0,False,False,True

In [12]:
# Divisão em sets de treinamento/teste (Regra de Pareto - 80/20 - Ref. https://pt.wikipedia.org/wiki/Princ%C3%ADpio_de_Pareto)
X_train, X_test, y_train, y_test = train_test_split(df_one_hot.drop('label', axis=1), df_one_hot['label'], test_size=0.2, random_state=42)

In [13]:
len(X_train.columns)

7

In [14]:
# Construção de nosso modelo usando Regressão Logística (Ref. https://edisciplinas.usp.br/pluginfile.php/3769787/mod_resource/content/1/09_RegressaoLogistica.pdf)
clf = LogisticRegression(max_iter=20).fit(X_train, y_train)

# Predição em dados de teste
y_pred = clf.predict(X_test)

In [15]:
# Avaliação de Acurácia, Precisão e Recall de nosso modelo
accuracy = accuracy_score(y_pred, y_test)
precision = precision_score(y_pred, y_test)
recall = recall_score(y_pred, y_test)

print("acuracia", accuracy)
print("precisao", precision)
print("recall", recall)

acuracia 1.0
precisao 1.0
recall 1.0

In [16]:
# Utilizando Árvore de Decisão
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

# Avaliação de Acurácia, Precisão e Recall de nosso modelo
accuracy = accuracy_score(y_pred, y_test)
precision = precision_score(y_pred, y_test)
recall = recall_score(y_pred, y_test)

print("acuracia", accuracy)
print("precisao", precision)
print("recall", recall)

acuracia 1.0
precisao 1.0
recall 1.0